Fix pf log message format while flushing and add missing argument
It was reported by go test while executing the `test` target.

```
$ gmake -f Makefile
./pf.go:88:3: Errorf format %s reads arg #3, but call has 2 args
gmake: *** [Makefile:41: test] Error 2
```